# Generated by Django 3.1.5 on 2021-01-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210106_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.URLField(default='https://res.cloudinary.com/riceev/image/upload/v1610414744/Birthdays/Admin/baby1_yunb94.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://res.cloudinary.com/riceev/image/upload/v1610414744/Birthdays/Admin/baby1_yunb94.jpg', max_length=255),
        ),
    ]
