# Generated by Django 3.1.5 on 2021-01-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210112_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.URLField(default='https://res.cloudinary.com/riceev/image/upload/v1610414643/Birthdays/Admin/landscape_unylg7.jpg', max_length=255),
        ),
    ]
