#!/bin/sh
#Deployment script
#Description: Runs commands required for a deployment
#Author: Aminu Mohammed Olawale
#Date: 10/01/2021


git pull 

cd frontend/

npm run build

cd ..

source /home/aminuolawale/.cache/pypoetry/virtualenvs/birthdays-V3988U0m-py3.8/bin/activate

python manage.py collectstatic

exit

sudo systemctl restart nginx




