# Generated by Django 3.1.3 on 2020-11-26 19:26

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrant', models.CharField(max_length=100)),
                ('cover_image', django.contrib.postgres.fields.hstore.HStoreField()),
                ('extra_images', django.contrib.postgres.fields.ArrayField(
                    base_field=django.contrib.postgres.fields.hstore.HStoreField(), default=list, size=None)),
                ('date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
