# Generated by Django 3.1.3 on 2020-11-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
