# Generated by Django 3.1.3 on 2020-11-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0003_auto_20201127_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='extra_images',
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cover', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('caption', models.CharField(default='', max_length=100)),
                ('src', models.CharField(max_length=255)),
                ('celebrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthdays.birthday')),
            ],
        ),
    ]
