# Generated by Django 3.1.3 on 2020-12-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0003_auto_20201222_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
