# Generated by Django 3.1.3 on 2020-11-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0004_auto_20201127_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='celebrant',
            new_name='birthday',
        ),
    ]
