# Generated by Django 3.1.3 on 2020-11-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0005_auto_20201127_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='src',
            new_name='files',
        ),
    ]
