# Generated by Django 3.1.3 on 2020-11-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0006_auto_20201127_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='files',
            new_name='file',
        ),
    ]
