# Generated by Django 3.1.3 on 2020-11-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0007_auto_20201127_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='birthday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='birthdays.birthday'),
        ),
    ]
