# Generated by Django 3.1.3 on 2020-12-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0009_auto_20201127_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='Picture',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='celebrant',
        ),
        migrations.CreateModel(
            name='Celebrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('birthday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrant', to='birthdays.birthday')),
            ],
        ),
    ]
