# Generated by Django 3.1.3 on 2020-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0010_auto_20201201_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrant',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
