# Generated by Django 3.1.3 on 2020-12-01 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0011_auto_20201201_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrant',
            name='birthday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='celebrant', to='birthdays.birthday'),
        ),
    ]
